# Generated by Django 5.2 on 2025-07-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_address_profile_city_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '  حساب کاربری', 'verbose_name_plural': 'حساب های کاربری'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(default='nadare', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='meli_code',
            field=models.CharField(default=1111111111, max_length=10),
        ),
    ]
