# Generated by Django 5.1.3 on 2025-05-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_alter_article_title_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='floatfield',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='myfile',
            field=models.FileField(default=1, upload_to='blog/file/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
